config/routes.rb
MailDemo::Application.routes.draw do
  root 'users#welcome'
  get'sign_up' => 'users#new', :as => :new_user
  resources :users, only:[:create]
  delete 'sign_out' => 'auths#destroy', :as => :auths
  get 'sign_in' => 'auths#new', :as => :new_auth
  resources :auths, only:[:create]

end

app/models/user.rb
require 'bcrypt'
class User
  include Mongoid::Document
  attr_accessor :password, :password_confirmation
  field :username, type: String
  field :email, type: String
  field :hashed_password, type: String

  before_save :hash_the_password
  def passes_authentication? (password_to_check)
    BCrypt::Password.new(self.hashed_password).is_password?(password_to_check)
  end

############
  private
############

  def hash_the_password
    #
    self.hashed_password = BCrypt::Password.create(self.password)
    self.password = self.password_confirmation = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  helper_method :current_user
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    end
  end
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  def new
    if current_user
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user.passes_authentication?(params[:user][:password])
      #
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to new_auth_path
      flash[:notice] = "Invalid username/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_auth_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    unless current_user
      @user = User.new(user_params)
      if @user.password == @user.password_confirmation
        @user.save
        redirect_to root_path
        flash[:notice] = "A confirmation e-mail has been sent to your account"
      else
        redirect_to new_user_path
        flash[:notice] = "Password and password confirmation did not match"
      end
    else
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auths/new.html.erb
<p id = "notice"><%= notice %></p>
<h1>Sign In</h1>
<%= form_for @user, {url:'/auths',method:'post'} do |f| %>
  <%= f.text_field :username, :placeholder => 'Username' %>
  <%= f.password_field :password, :placeholder => 'Password' %>
  <%= f.submit "Sign In" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MailDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<p id = "notice"><%= notice %></p>
<h1>New User</h1>

<%= form_for @user do |f| %>
  <div class = "field cf">
    <%= f.label :post, "Username" %>
    <%= f.text_field :username %>
  </div>
  <div class = "field cf">
    <%= f.label :post, "E-Mail Address" %>
    <%= f.email_field :email %>
  </div>
  <div class = "field cf">
    <%= f.label "Password" %>
    <%= f.password_field :password %>
  </div>
  <div class = "field cf">
    <%= f.label :post, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Sign Up", {class: 'submit'} %>
<% end %>

app/views/users/welcome.html.erb
<p id = "notice"><%= notice %></p>
<h1>Welcome!</h1>

<h2>Our current user has...</h2>

<% if current_user %>
  <p><%= "a username of #{current_user.username}" %></p>
<% else %>
  <p>not logged in... <%= link_to 'change that', new_auth_path %></p>
<% end %>

<p><%= current_user ? (link_to 'Sign Out', auths_path, {method: :delete}) : (link_to 'Need to make an account?', new_user_path) %></p>